[package]
name = "e2e-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy.workspace = true
async-trait.workspace = true
aws-config.workspace = true
aws-sdk-s3.workspace = true
aws-sdk-sqs.workspace = true
color-eyre.workspace = true
dotenvy.workspace = true
httpmock.workspace = true
log = "0.4.21"
orchestrator.workspace = true
reqwest = { workspace = true, features = ["json"] }
serde_json.workspace = true
testcontainers.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-stream.workspace = true
tokio-util.workspace = true
url.workspace = true

[[test]]
name = "test_samples"
path = "tests.rs"
